baseURL = "https://yura.sycx.me/"
languageCode = "ja"
author= "udspj"
title = "ゆらゆら魔法少女"
theme = "hyde-hyde"

googleAnalytics= "UA-19868922-4"

[params]

themeColor = "theme-base-0c"
Author = "udspj"

  